// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyCursorTweaks(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(1987220350).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ConfigDir(): $CancellablePromise<string> {
    return $Call.ByID(77373268);
}

export function ExportCAPEM(): $CancellablePromise<string> {
    return $Call.ByID(3979319461);
}

export function GetCursorSettingsStatus(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(294038120).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetState(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2985438978).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUsageStats returns the aggregate token-use snapshot the Stats tab in the
 * Wails UI renders. Computed on demand from disk; safe to call any time
 * (even while the proxy is stopped — history persists across restarts).
 */
export function GetUsageStats(): $CancellablePromise<$models.UsageStats> {
    return $Call.ByID(1746416095).then(($result: any) => {
        return $$createType2($result);
    });
}

export function InstallCA(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2432803218).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadUserConfig(): $CancellablePromise<$models.UserConfig> {
    return $Call.ByID(3829929914).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenSettingsFolder(): $CancellablePromise<void> {
    return $Call.ByID(1745916518);
}

export function RevertCursorTweaks(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(3063858870).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveUserConfig(cfg: $models.UserConfig): $CancellablePromise<void> {
    return $Call.ByID(2912765815, cfg);
}

export function SetBaseURL(url: string): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(3562908193, url).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetStateCallback(cb: any): $CancellablePromise<void> {
    return $Call.ByID(848980353, cb);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(1549492893);
}

export function StartProxy(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(1771136707).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StopProxy(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2242619817).then(($result: any) => {
        return $$createType1($result);
    });
}

export function TestAdapter(index: number): $CancellablePromise<$models.ModelAdapterConfig> {
    return $Call.ByID(94462378, index).then(($result: any) => {
        return $$createType4($result);
    });
}

export function UninstallCA(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(1616856875).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CursorSettingsStatus.createFrom;
const $$createType1 = $models.ProxyState.createFrom;
const $$createType2 = $models.UsageStats.createFrom;
const $$createType3 = $models.UserConfig.createFrom;
const $$createType4 = $models.ModelAdapterConfig.createFrom;
