// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyCursorTweaks(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(1987220350).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ConfigDir(): $CancellablePromise<string> {
    return $Call.ByID(77373268);
}

export function ExportCAPEM(): $CancellablePromise<string> {
    return $Call.ByID(3979319461);
}

/**
 * GetCloseAction returns the persisted close-behaviour preference
 * ("" = ask, "quit", "tray"). Unbound errors from config.json are swallowed
 * — a missing or malformed config just maps to "ask the user".
 */
export function GetCloseAction(): $CancellablePromise<string> {
    return $Call.ByID(4246659013);
}

export function GetCursorSettingsStatus(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(294038120).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetState(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2985438978).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUsageStats returns the aggregate token-use snapshot the Stats tab in the
 * Wails UI renders. Computed on demand from disk; safe to call any time
 * (even while the proxy is stopped — history persists across restarts).
 */
export function GetUsageStats(): $CancellablePromise<$models.UsageStats> {
    return $Call.ByID(1746416095).then(($result: any) => {
        return $$createType2($result);
    });
}

export function InstallCA(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2432803218).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadUserConfig(): $CancellablePromise<$models.UserConfig> {
    return $Call.ByID(3829929914).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenSettingsFolder(): $CancellablePromise<void> {
    return $Call.ByID(1745916518);
}

/**
 * RequestHide triggers the registered hide-to-tray callback. Called from
 * the frontend close dialog's "Minimize to tray" button.
 */
export function RequestHide(): $CancellablePromise<void> {
    return $Call.ByID(2986251096);
}

/**
 * RequestQuit triggers the registered quit callback. Called from the
 * frontend close dialog's "Quit" button. Runs the callback on its own
 * goroutine so the Wails RPC returns before the app actually tears down.
 */
export function RequestQuit(): $CancellablePromise<void> {
    return $Call.ByID(3981400551);
}

export function RevertCursorTweaks(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(3063858870).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveUserConfig(cfg: $models.UserConfig): $CancellablePromise<void> {
    return $Call.ByID(2912765815, cfg);
}

export function SetBaseURL(url: string): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(3562908193, url).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetCloseAction persists the user's choice from the close dialog. "quit"
 * and "tray" are the only meaningful values; anything else is normalised
 * to "" (which makes the dialog reappear on the next close — a safe reset).
 */
export function SetCloseAction(action: string): $CancellablePromise<void> {
    return $Call.ByID(1124812073, action);
}

/**
 * SetHideCallback registers the function main.go uses to hide the main
 * window to the system tray (keeping the proxy and tray icon alive).
 */
export function SetHideCallback(cb: any): $CancellablePromise<void> {
    return $Call.ByID(2449416262, cb);
}

/**
 * SetQuitCallback registers the function main.go uses to fully tear the
 * app down (Stop proxy, remove tray icon, quit the Wails application).
 * Invoked from RequestQuit so the frontend close dialog can exit cleanly.
 */
export function SetQuitCallback(cb: any): $CancellablePromise<void> {
    return $Call.ByID(1385398785, cb);
}

export function SetStateCallback(cb: any): $CancellablePromise<void> {
    return $Call.ByID(848980353, cb);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(1549492893);
}

export function StartProxy(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(1771136707).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StopProxy(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2242619817).then(($result: any) => {
        return $$createType1($result);
    });
}

export function TestAdapter(index: number): $CancellablePromise<$models.ModelAdapterConfig> {
    return $Call.ByID(94462378, index).then(($result: any) => {
        return $$createType4($result);
    });
}

export function UninstallCA(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(1616856875).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CursorSettingsStatus.createFrom;
const $$createType1 = $models.ProxyState.createFrom;
const $$createType2 = $models.UsageStats.createFrom;
const $$createType3 = $models.UserConfig.createFrom;
const $$createType4 = $models.ModelAdapterConfig.createFrom;
